### ISSUE TITLE
Article 9 : Layouts and their types

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/Eazy-Android#25]
Explain the term Layout and also different types of Layouts in Android along with their use cases in laymen terms.

**Comment by RockingRishav** [comment]
I would like to work upon this, please assign it to me.

**Comment by apoorva1823000** [comment]
I would like to work upon this, kindly assign it to me

**Comment by apoorva1823000** [comment]
Hi, do where I need to write the article ? and should it be in md format or normal text ?
Kindly guide
