### ISSUE TITLE
Article 10 : Android UI Controls

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/Eazy-Android#26]
Write about the 13 types of UI Controls in Android in simple terms.

**Comment by RockingRishav** [comment]
Hey @utkarsh006  can you assign this issue to me as part of Hacktoberfest.

**Comment by utkarsh006** [comment]
@RockingRishav Contributing period starts from Oct 1 then I will assign you.

**Comment by RockingRishav** [comment]
Okay Thanks.

**Comment by RockingRishav** [comment]
Please assign me this issue.

**Comment by pandeatul27** [comment]
Hey, @utkarsh006  I want to contribute to this issue. Can you assign it to me under hacktoberfest?

**Comment by harshxtanwar** [comment]
Hey, @utkarsh006 I would love to contribute to this issue. Can you assign it to me?
