### ISSUE TITLE
Article 12 : Styles and Themes in Android

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/Eazy-Android#35]
- Create a documentation that explains the above topic in simple terms.
- Try to avoid language used in articles, write it on your own terms.
- Give examples where necessary.

**Comment by RockingRishav** [comment]
I want to work upon this issue Can You assign it to me?

**Comment by utkarsh006** [comment]
@RockingRishav One contributor will work on one issue at a time. Kindly don't repeat this activity in future.

**Comment by apoorva1823000** [comment]
@utkarsh006 I would like to work upon this, kindly assign it to me

**Comment by atom540** [comment]
I want to work on this issue can you please assign it to me?

**Comment by vinitfreakk** [comment]
I would really like to work on this

**Comment by cadamini** [comment]
Good resources: 
- https://developer.android.com/develop/ui/views/theming/themes#:~:text=A%20style%20is%20a%20collection,not%20just%20an%20individual%20view.
- https://www.tutorialspoint.com/android/android_styles_and_themes.htm
- https://medium.com/androiddevelopers/android-styling-themes-vs-styles-ebe05f917578

**Comment by harshxtanwar** [comment]
hello @utkarsh006 can I get assigned to this issue? I would love to work on it.
