### ISSUE TITLE
Article 1 : Why Kotlin is preferred over Java for Android?

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/Eazy-Android#38]
- Write an article on the above topic.
- Give 5 reasons to justify your answer.
- Explain each point in detail.

**Comment by Yash-Goyal007** [comment]
Would you like to assign this issue to me?...

**Comment by apoorva1823000** [comment]
I have already submitted one article i.e of layout and its types
Can I work on this another one too?

**Comment by utkarsh006** [comment]
@apoorva1823000 Firstly I'm very glad to see your participation at this level. But issues are assigned on First Come first serve basis.

**Comment by Yash-Goyal007** [comment]
Hey can you please tell me why my PR is invalid?

**Comment by utkarsh006** [comment]
@Yash-Goyal007 I have mentioned it in your PR.

**Comment by vinitfreakk** [comment]
I would be like to contribute in this
