### ISSUE TITLE
⭐ Note for all Contributors ⭐

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/Eazy-Android#40]
We regret to inform you that, our repo is no longer being considered for Hacktoberfest 2022. However, we appreciate your efforts and time in engaging with the repo. 
- If you want to contribute you can, as this repo will be a boon for Android Enthusiasts.
- Sole purpose of open source is to uplift and we will keep doing that.

Signing off,
Utkarsh Saxena

**Comment by HawkItzme** [comment]
Sad to here that bro, but it's a great Repo that can help new Android Developers who are keen to learn. Will put my effort to contribute here too.

**Comment by utkarsh006** [comment]
@HawkItzme Thanks buddy. Good to see people like you in the community.
